### PR TITLE
fixed missing logo Readme.md

### PR DESCRIPTION
**Pull request by oscarmorrison**

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@kevinburke

**Comment by oscarmorrison** [comment]
@kevinburke can you please merge

**Comment by oscarmorrison** [comment]
@pavelloz can you merge?

**Comment by pavelloz** [comment]
Nope, sorry, I don't have write access.

**Comment by oscarmorrison** [comment]
Thanks anyway. @kevinburke

**Comment by kevinburke** [comment]
Merged as 8211cce. Sorry :(

**Pull request closed without merging**
